### ISSUE TITLE
F-mode only shows 2 and 3

### ISSUE THREAD

**Issue by ror1948** [frankiearzu/DSMTools#11]
edgetx 2.8.5 date 2023-08-04 time 09;49;14
did all the setup but my ch5 fmode only shows FM2 and FM3 in the FP setup
once I saw it display 191 instead of 1 and when I switched ch5 once all I saw was 2 or 3
2 was showing in pos 1 as well as pos 2
my ch5 is going from -100 to +100

i tried 0.54 all releases
also tried 0.55 prerelease

**Comment by ror1948** [comment]
TX16s

**Comment by ror1948** [comment]
Rx is AR637t with latest firmware

**Comment by frankiearzu** [comment]
Please check that "Enable Max Throw" if OFF in the module settings (where you do bind).    If is ON, it will shift the servo range and you will never get Flight mode 1

**Comment by txkflier** [comment]
I wish the EdgeTX developers would make their OS show the true pulse width in Spektrum mode.

**Comment by frankiearzu** [comment]
Not a script problem
