### ISSUE TITLE
DSM_Telemetry_v11 - DSM_SmartRX_Tel.lua typo

### ISSUE THREAD

**Issue by qsiguy** [frankiearzu/DSMTools#13]
Menu text for "Flight Pack" shows "Fligh Pack".  Edit line 598 DSM_SmartRX_Tel.lua script.
![SmartRX typo](https://github.com/frankiearzu/DSMTools/assets/75959828/8dffa81e-ef75-4fb5-83bb-3e70a9e188a8)

Fix (Notepad ++)
![SmartRX typo fix](https://github.com/frankiearzu/DSMTools/assets/75959828/be5db4b1-b9cb-49fb-84fd-8c4ccd4c07e3)

-Shane's DIY

**Comment by frankiearzu** [comment]
Fixed in version 1.2 as well as adding extra line for TextGen
