### ISSUE TITLE
[Request] Ethos compatibility

### ISSUE THREAD

**Issue by mszulen** [frankiearzu/DSMTools#18]
Is there a chance for Ethos compatibility of the tool?
Thanks!

**Comment by frankiearzu** [comment]
Really don't know what it would take. don't have a FrSky radio.
Also there is a lot of plumbing in the EdgeTX firmware to support the Multi-Module and Forward Programming beside the LUA scripts.

**Comment by mszulen** [comment]
Thanks for a quick answer. I wasn't aware of the patches. The multimodule itself is working with Ethos (Frsky have provided the basic LUA). Now, the situation is more clear to me. Thanks again!

**Comment by Crunch69** [comment]
FrSky uses multi module and would also require forward programming.  It would be great to add this to ethos

**Comment by Guy559** [comment]
This seems like a terrific tool. 2nd the desire to see it ported to include Ethos.

**Comment by Crunch69** [comment]
Is DSM tools tightly integrated with multi module if it is would it be easier since multi module is already working with full Telemetry in ethos?

**Comment by frankiearzu** [comment]
Will track it on duplicate ticker #21
