### ISSUE TITLE
FP does not work on Spektrum AR631 V2 Rx

### ISSUE THREAD

**Issue by ror1948** [frankiearzu/DSMTools#22]
limited menu on ar631 v2
not enough to program Rx.
when i try to enter forward programming option on Rx it says no DSM compatible Rx present.

**Comment by frankiearzu** [comment]
Didn't know that there was a V2.
Verify the following:
1. That is using DSM-X2F protocol
2. Make sure that you are receiving telemetry data; do discover sensors and see that they are refreshing.

By any chance do you have the USB programmer? To verify the firmware version or upgrade it to the latest.

**Comment by ror1948** [comment]
yes i have usb programmer and i have already updated to latest(2.48.the V2 shows up when i go into Spektrum programmerFP works ok on my updated(2024) DX9 Tx






I was not using X2F
i tried X2F and it seems to be working nowyes telemetry is there and updating.
thanks
    On Friday, June 21, 2024 at 11:10:30 p.m. EDT, Frankie Arzu ***@***.***> wrote:  
 
 


Didn't know that there was a V2.
Verify the following:
   
   - That is using DSM-X2F protocol
   - Make sure that you are receiving telemetry data; do discover sensors and see that they are refreshing.

By any chance do you have the USB programmer? To verify the firmware version or upgrade it to the latest.

**Comment by frankiearzu** [comment]
Ron, did not understand your last message.  Did it work after binding using DSM-X2F??

**Comment by ror1948** [comment]
yesthanks
    On Friday, June 21, 2024 at 11:27:29 p.m. EDT, Frankie Arzu ***@***.***> wrote:  
 
 


Ron, did not understand your last message. Did it work after binding using DSM-X2F??
