### ISSUE TITLE
Changing channel setup from "Ihn" to "SLRX2" gives an Error

### ISSUE THREAD

**Issue by TheFab21** [frankiearzu/DSMTools#23]
Hi Frankie,
Changing channel setting from inh  to SLRX2 (and reverse) on a AR8020T with 2.48 fw, works but getting a error at the end (nil expectet),
using edgetx 2.10.2 on a tx16s, and dsmtool color 0.59
I've check with a spektrum TX and the setting change is taken in account,
regards

**Comment by frankiearzu** [comment]
I was able to duplicate.. don't know why when updating that line, the RX is sending an 2nd confirmation of EDIT but for a menu line that is not part of the menu. For all the other lines, it does not do the 2nd confirmation..
Easy fix just to ignore the 2nd confirmation, but will check if the same thing happens with genuine Spektrum TX.

**Comment by frankiearzu** [comment]
Looks like my change for #25 fix this problem too.

**Comment by TheFab21** [comment]
Cool thanks FrankieFabrice SantoniChemin Frank Thomas, 621223 COLOGNYSUISSETel. : +41 (0)22 736 45 23mob : +41 (0)79 641 61 27Le 19 août 2024 à 07:04, Frankie Arzu ***@***.***> a écrit :﻿
Looks like my change for #25 fix this problem too.

**Comment by frankiearzu** [comment]
Try my "In-development" tool.  Is stable, and fixes 2 small problems.
https://github.com/frankiearzu/DSMTools/tree/main/DSM%20Forward%20Programming/In%20Development

**Comment by frankiearzu** [comment]
![image](https://github.com/user-attachments/assets/998e23e9-56f2-4304-b089-731ba2d4afd0)
