### ISSUE TITLE
SD_FP_59_COLOR_Aug24.zip may have captured an obsolete version of DsmModelLib.lua

### ISSUE THREAD

**Issue by zen3d** [frankiearzu/DSMTools#27]
I installed SD_FP_59_COLOR_Aug24.zip, which may have captured an obsolete version of DsmModelLib.lua from 2023. When I try to run that plugin, it crashes EdgeTX 2.10.* when I try to perform forward programming. When I clone the repo and copy the files directly, the plugin no longer crashes.

**Comment by frankiearzu** [comment]
Just installed clean from a downloaded zip file, and is working fine.  
The DsmModelLib haven't changed in a long time, so thats why the date of Nov 2023. 
I usually delete the DSMLIB and the main color program before copying the new files.
Running EdgeTX 2.10.3

**Comment by zen3d** [comment]
Thanks
