### ISSUE TITLE
AR631 Gyro Unresponsive | v3.x.x Firmware + v59 DSMTools

### ISSUE THREAD

**Issue by ryanbender2** [frankiearzu/DSMTools#31]
I recently got the new AS3X+ AR631 RX. I did a factory reset and went through the initial first time setup + the initial safe setup. However, when enabling SAFE to self-level to one of the flight modes and use that flight mode, nothing actually happens on the plane. It's as if it was never enabled, but it very clearly is. I got 5 AR631's, all with the new 3.x.x firmware, went through the exact same process on all 5. 1 of them worked, all others were unresponsive in safe.

I'm using a RadioMaster TX16S.

**Comment by txkflier** [comment]
Make sure "Enable max throw" is turned off. When it's on, the travel is increased which causes the values for flight modes to be wrong.
