### ISSUE TITLE
F8 error with AR8020T spektrum Rx

### ISSUE THREAD

**Issue by ror1948** [frankiearzu/DSMTools#4]
same error as v 0.53
![v54error](https://user-images.githubusercontent.com/98917767/231228642-fc5319a9-c3cf-462f-9b5a-6430b70c60e7.jpg)

**Comment by ror1948** [comment]
put it works as intended if you select the F8 error menu displayed

**Comment by frankiearzu** [comment]
@ror1948:  When i released v0.54 it did not have the changes for that message..  i was explaning to you how to add them yourself.  Just update the file in the release dated April11 on the site with the changes needed for that menu to show up... I put the message F8 as "Settings".. thats my best guest.  if someone you know has a Spektrum TX and that RX.. we can see what is the proper text and correct it later.

**Comment by ror1948** [comment]
i have dx9 and will try and get info...
thanks
