### ISSUE TITLE
unable to select FM channel higher than ch6 on AR637

### ISSUE THREAD

**Issue by ror1948** [frankiearzu/DSMTools#7]
version 0.54 on a TX16s and Rx is a AR637T
Unable to select any channel higher than ch6 as FM CHANNEL for mode control.
I believe the AR637T has 9 channels but it is best to NOT check the range of channel entered.
Leave that up to the programmer.

**Comment by qsiguy** [comment]
I believe to use channel 7+ have your switch programmed for the channel and rather selecting the channel in forward programming just click it and then flip the switch to auto select.  Then it should retain the correct channel.

**Comment by qsiguy** [comment]
I just posted a video on my channel how to do this.

https://youtu.be/jLRE6MVU2hU

**Comment by frankiearzu** [comment]
Is documented that you need to use the switches in this case,
