### ISSUE TITLE
Bad Argument #1 Error

### ISSUE THREAD

**Issue by checkmatehau** [frankiearzu/DSMTools#8]
When trying to use DSM Forward Programming (Color+Touch) on my Radiomaster TX16s with EdgeTX, I get the following script syntax error popup:

`bad argument #1 to 'write' (FILE* expected, got nil)`

I am assuming this has to do with the file structure. How do I resolve this issue?

**Comment by qsiguy** [comment]
What were you attempting to do when you received this message?  If during the model setup, which isn't actually in forward programming, perhaps you don't have the "/MODELS/DSMDATA" folder created?  When you do the model setup it writes a .txt file to that folder and if the folder does not exist you'd get an error.

**Comment by checkmatehau** [comment]
I am an idiot and did not install ALL of the folders. I thought just the ones for Color+Touch were required. Closed.

**Comment by frankiearzu** [comment]
Thank you guys for helpin!
